server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nbowow/spring-cloud-config.git
#          username: [your username] -> repository private?? ???? ??
#          password: [your password]
#          uri: file://C:/Users/SSAFY/Desktop/Nam/SpringCloud_MSA/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
