pipeline {
    agent any

    environment {
        BACKEND_DIR = './discovery_service'
        DOCKER_IMAGE_BACKEND = 'parkgc0504/discovery-service:latest'
        GITLAB_CREDENTIALSID = 'gichangssafy'
        DOCKERHUB_CREDENTIALS = 'dockerhub-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: GITLAB_CREDENTIALSID, branch: 'master', url: 'https://lab.ssafy.com/s11-bigdata-dist-sub1/S11P21C206.git'
            }
        }

        stage('Notify Start') {
            steps {
                script {
                    def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                    def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                    mattermostSend(
                        color: 'warning',
                        message: "discovery_service 빌드 시작: ${env.JOB_NAME} #${env.BUILD_NUMBER} \n(<${env.BUILD_URL}|Details>)",
                        endpoint: 'https://meeting.ssafy.com/hooks/rqoymdqdtjr4dqhkai1gmnnunh',
                        channel: 'C206_deploy'
                    )
                }
            }
        }


        stage('Build discovery_service') {
            when {
                changeset "discovery_service/**"  // backend 폴더에 변경 사항이 있을 때만 실행
            }
            steps {
                dir(BACKEND_DIR) {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker Build and Push discovery_service to DockerHub') {
            when {
                changeset "discovery_service/**"  // backend 폴더에 변경 사항이 있을 때만 실행
            }
            steps {
                dir(BACKEND_DIR) {
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', DOCKERHUB_CREDENTIALS) {
                            def backendImage = docker.build(DOCKER_IMAGE_BACKEND)
                            backendImage.push()
                        }
                    }
                }
            }
        }

        stage('Deploy Locally') {
            when {
                changeset "discovery_service/**"  // backend 폴더에 변경 사항이 있을 때만 실행
            }
            steps {
                script {
                    // 기존 컨테이너 중지 및 삭제
                    sh 'docker stop discovery-service || true'
                    sh 'docker rm discovery-service || true'

                    // 새로운 컨테이너 실행
                    sh '''
                    docker run -d -p 8761:8761 --network backendnet \
                    -e "spring.cloud.config.uri=http://config-service:8888" \
                    --name discovery-service parkgc0504/discovery-service:latest
                    '''
                }
            }
        }

    }

    post {
        success {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend(color: 'good',
                    message: "discovery_service 빌드 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}\n(<${env.BUILD_URL}|Details>)",
                    endpoint: 'https://meeting.ssafy.com/hooks/rqoymdqdtjr4dqhkai1gmnnunh',
                    channel: 'C206_deploy'
                )
            }
        }
        failure {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend(color: 'danger',
                    message: "discovery_service 빌드 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}\n(<${env.BUILD_URL}|Details>)",
                    endpoint: 'https://meeting.ssafy.com/hooks/rqoymdqdtjr4dqhkai1gmnnunh',
                    channel: 'C206_deploy'
                )
            }
        }
    }
}
